frontend:
 build: ./../frontend
 container_name: justdoit-frontend-container
 working_dir: /code/justdoit/src
 hostname: frontend
 ports:
   - 8080:80
 environment:
   - SRC_PATH=/code/justdoit/src
   - NGINX_HOST=localhost
   - NGINX_PORT=80
 volumes:
   - ./../frontend:/code/justdoit/src
   - ./../frontend/dist:/usr/share/nginx/html:ro
   - ./../frontend/docker-config:/tmp/justdoit
 command: /bin/bash -c 'cd $$SRC_PATH; npm run clean; npm install; npm run build:prod; nginx -g "daemon off;"'
 restart: always
